development:
  adapter: postgis
  encoding: unicode
  database: best_nyc_schools_development
  pool: 5
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'

test:
  adapter: postgis
  encoding: unicode
  database: best_nyc_schools_test
  pool: 5
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'

